<section class="intro">
    <div class="swiper-container">

        <div class="swiper-wrapper">
            <div class="swiper-slide">
                <div class="container-sm">
                    <h1 class="title">Tees &amp; Tops</h1>
                    <p class="desc">
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                        pariatur.
                    </p>
                    <a href="#" class="btn">Discover more</a>
                </div>
            </div>
            <div class="swiper-slide">
                <div class="container-sm">
                    <h1 class="title">Outerwear</h1>
                    <p class="desc">
                        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                        pariatur. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ducimus a expedita iure optio, cupiditate maxime!
                    </p>
                    <a href="#" class="btn">Discover more</a>
                </div>
            </div>
        </div>

        <div class="swiper-pagination"></div>
        <div class="swiper-button-pr">
            <svg class="swiper__svg" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 129 129">
                <g>
                    <path d="m88.6,121.3c0.8,0.8 1.8,1.2 2.9,1.2s2.1-0.4 2.9-1.2c1.6-1.6 1.6-4.2 0-5.8l-51-51 51-51c1.6-1.6 1.6-4.2 0-5.8s-4.2-1.6-5.8,0l-54,53.9c-1.6,1.6-1.6,4.2 0,5.8l54,53.9z"/>
                </g>
            </svg>
        </div>
        <div class="swiper-button-nx">
            <svg class="swiper__svg" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 129 129" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 129 129">
                <g>
                    <path d="m40.4,121.3c-0.8,0.8-1.8,1.2-2.9,1.2s-2.1-0.4-2.9-1.2c-1.6-1.6-1.6-4.2 0-5.8l51-51-51-51c-1.6-1.6-1.6-4.2 0-5.8 1.6-1.6 4.2-1.6 5.8,0l53.9,53.9c1.6,1.6 1.6,4.2 0,5.8l-53.9,53.9z"/>
                </g>
            </svg>
        </div>
    </div>
</section>